name: Deploy Outsider Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust as needed
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build
