name: Deploy Outsider Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust as needed
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Create tarball
        run: tar --no-same-permissions -cvf publish.tar dist/
      
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          source: "dist/"
          target: "/var/www/html/"

      - name: Rename directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VM_HOST}}
          username: ${{secrets.VM_USERNAME}}
          password: ${{secrets.VM_PASSWORD}}
          script: |
            echo "${{ secrets.VM_PASSWORD }}" | sudo -S mv dist Outsider.Web
        env:
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
